// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class LlamaError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "LlamaError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? LlamaError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsMessages(lhsKey, rhsKey) {
          if deepEqualsMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Why a generation run stopped.
enum FinishReason: Int {
  /// The model produced an end-of-generation token.
  case eogToken = 0
  /// The run reached [GenerationRequest.maxTokens].
  case maxTokens = 1
  /// A [GenerationRequest.stopSequences] entry matched.
  case stopSequence = 2
  /// The context window filled before the run ended naturally.
  case contextFull = 3
  /// The run was cancelled via [LlamaHostApi.cancelGeneration].
  case cancelled = 4
  /// The native runtime ended the run early after an unrecoverable internal
  /// condition (e.g. a failed speculative rollback). Text streamed before
  /// this point is valid.
  case aborted = 5
}

/// Parameters for an optional drafter (assistant) model that enables
/// speculative decoding.
///
/// The drafter proposes tokens cheaply and the main model verifies them, so
/// the output distribution is identical to decoding with the main model
/// alone — just faster when the drafter's guesses are accepted. Any GGUF
/// whose vocabulary matches the main model works (e.g. a Gemma 4 MTP
/// `*-assistant` drafter); this is not tied to one architecture.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DraftModelOptions: Hashable {
  /// Absolute filesystem path to the drafter `.gguf`.
  var modelPath: String
  /// Number of drafter layers to offload to the GPU (`n_gpu_layers`).
  ///
  /// `0` forces CPU-only inference (e.g. the iOS Simulator).
  var gpuLayers: Int64
  /// Maximum tokens drafted per verification step.
  var maxDraftTokens: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DraftModelOptions? {
    let modelPath = pigeonVar_list[0] as! String
    let gpuLayers = pigeonVar_list[1] as! Int64
    let maxDraftTokens = pigeonVar_list[2] as! Int64

    return DraftModelOptions(
      modelPath: modelPath,
      gpuLayers: gpuLayers,
      maxDraftTokens: maxDraftTokens
    )
  }
  func toList() -> [Any?] {
    return [
      modelPath,
      gpuLayers,
      maxDraftTokens,
    ]
  }
  static func == (lhs: DraftModelOptions, rhs: DraftModelOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.modelPath, rhs.modelPath) && deepEqualsMessages(lhs.gpuLayers, rhs.gpuLayers) && deepEqualsMessages(lhs.maxDraftTokens, rhs.maxDraftTokens)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DraftModelOptions")
    deepHashMessages(value: modelPath, hasher: &hasher)
    deepHashMessages(value: gpuLayers, hasher: &hasher)
    deepHashMessages(value: maxDraftTokens, hasher: &hasher)
  }
}

/// Parameters for loading a GGUF model into a native llama.cpp session.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ModelLoadRequest: Hashable {
  /// Absolute filesystem path to the `.gguf` model.
  var modelPath: String
  /// Context window size (`n_ctx`).
  var contextSize: Int64
  /// Number of layers to offload to the GPU (`n_gpu_layers`).
  ///
  /// `0` forces CPU-only inference (e.g. the iOS Simulator).
  var gpuLayers: Int64
  /// Absolute path to the multimodal projector (`mmproj`) `.gguf`.
  ///
  /// When non-null the session also stands up an `mtmd` context, enabling
  /// image input via [GenerationRequest.images]. Null keeps the session
  /// text-only.
  var mmprojPath: String? = nil
  /// Vision-encoder token budget per image (mtmd `image_min_tokens` and
  /// `image_max_tokens`, both set to this value).
  ///
  /// Only meaningful with [mmprojPath], for vision models with dynamic
  /// resolution. Gemma supports 70, 140, 280, 560, or 1120; higher budgets
  /// trade prefill time for fidelity (1120 suits OCR / small text). Null
  /// keeps the model's metadata default. The physical batch is floored at
  /// this value so the encoder's non-causal image chunk fits one ubatch.
  var imageTokenBudget: Int64? = nil
  /// Optional drafter model enabling speculative decoding.
  ///
  /// Null disables speculation; the session then behaves exactly as a
  /// single-model session.
  var draftModel: DraftModelOptions? = nil
  /// Number of independent KV-cache sequences the context supports
  /// (`n_seq_max`). Null or `1` keeps the classic single-sequence session.
  ///
  /// With N sequences, [contextSize] is the TOTAL KV budget and each
  /// sequence gets `contextSize / N` positions. Generations target a
  /// sequence via [GenerationRequest.sequenceId]. Speculative decoding
  /// (draft models) only runs on sequence 0.
  var maxSequences: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ModelLoadRequest? {
    let modelPath = pigeonVar_list[0] as! String
    let contextSize = pigeonVar_list[1] as! Int64
    let gpuLayers = pigeonVar_list[2] as! Int64
    let mmprojPath: String? = nilOrValue(pigeonVar_list[3])
    let imageTokenBudget: Int64? = nilOrValue(pigeonVar_list[4])
    let draftModel: DraftModelOptions? = nilOrValue(pigeonVar_list[5])
    let maxSequences: Int64? = nilOrValue(pigeonVar_list[6])

    return ModelLoadRequest(
      modelPath: modelPath,
      contextSize: contextSize,
      gpuLayers: gpuLayers,
      mmprojPath: mmprojPath,
      imageTokenBudget: imageTokenBudget,
      draftModel: draftModel,
      maxSequences: maxSequences
    )
  }
  func toList() -> [Any?] {
    return [
      modelPath,
      contextSize,
      gpuLayers,
      mmprojPath,
      imageTokenBudget,
      draftModel,
      maxSequences,
    ]
  }
  static func == (lhs: ModelLoadRequest, rhs: ModelLoadRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.modelPath, rhs.modelPath) && deepEqualsMessages(lhs.contextSize, rhs.contextSize) && deepEqualsMessages(lhs.gpuLayers, rhs.gpuLayers) && deepEqualsMessages(lhs.mmprojPath, rhs.mmprojPath) && deepEqualsMessages(lhs.imageTokenBudget, rhs.imageTokenBudget) && deepEqualsMessages(lhs.draftModel, rhs.draftModel) && deepEqualsMessages(lhs.maxSequences, rhs.maxSequences)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ModelLoadRequest")
    deepHashMessages(value: modelPath, hasher: &hasher)
    deepHashMessages(value: contextSize, hasher: &hasher)
    deepHashMessages(value: gpuLayers, hasher: &hasher)
    deepHashMessages(value: mmprojPath, hasher: &hasher)
    deepHashMessages(value: imageTokenBudget, hasher: &hasher)
    deepHashMessages(value: draftModel, hasher: &hasher)
    deepHashMessages(value: maxSequences, hasher: &hasher)
  }
}

/// Parameters for a single generation run against a loaded session.
///
/// Generated class from Pigeon that represents data sent in messages.
struct GenerationRequest: Hashable {
  /// Session returned by [LlamaHostApi.loadModel].
  var sessionId: Int64
  /// The fully formatted prompt to feed the model.
  var prompt: String
  /// Hard cap on the number of tokens to generate.
  var maxTokens: Int64
  /// Sampling temperature; `0` is greedy.
  var temperature: Double
  /// Top-k cutoff applied before temperature sampling. Null or `<= 0`
  /// disables the top-k stage.
  var topK: Int64? = nil
  /// Nucleus (top-p) cutoff applied before temperature sampling. Null or
  /// `>= 1.0` disables the top-p stage.
  var topP: Double? = nil
  /// Sampler seed for reproducible generation. Null draws a random seed.
  var seed: Int64? = nil
  /// Strings that, when produced in the decoded output, halt generation.
  ///
  /// The matched stop sequence is removed from the streamed text and is not
  /// emitted. Matching runs against the decoded text (with special tokens
  /// rendered), so control markers such as Gemma's `<turn|>` work directly.
  /// Empty disables stop-sequence handling.
  var stopSequences: [String]
  /// Encoded image bytes (PNG/JPEG) to feed alongside [prompt].
  ///
  /// Each entry corresponds, in order, to one media marker in [prompt]. Only
  /// honoured when the session was loaded with a
  /// [ModelLoadRequest.mmprojPath]; otherwise ignored. Null or empty runs a
  /// text-only generation.
  var images: [FlutterStandardTypedData]? = nil
  /// KV-cache sequence this generation runs in. Null means sequence 0.
  ///
  /// Only meaningful when the session was loaded with
  /// [ModelLoadRequest.maxSequences] > 1; each sequence keeps its own
  /// prompt-prefix cache. Speculative decoding is bypassed for non-zero
  /// sequences.
  var sequenceId: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenerationRequest? {
    let sessionId = pigeonVar_list[0] as! Int64
    let prompt = pigeonVar_list[1] as! String
    let maxTokens = pigeonVar_list[2] as! Int64
    let temperature = pigeonVar_list[3] as! Double
    let topK: Int64? = nilOrValue(pigeonVar_list[4])
    let topP: Double? = nilOrValue(pigeonVar_list[5])
    let seed: Int64? = nilOrValue(pigeonVar_list[6])
    let stopSequences = pigeonVar_list[7] as! [String]
    let images: [FlutterStandardTypedData]? = nilOrValue(pigeonVar_list[8])
    let sequenceId: Int64? = nilOrValue(pigeonVar_list[9])

    return GenerationRequest(
      sessionId: sessionId,
      prompt: prompt,
      maxTokens: maxTokens,
      temperature: temperature,
      topK: topK,
      topP: topP,
      seed: seed,
      stopSequences: stopSequences,
      images: images,
      sequenceId: sequenceId
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      prompt,
      maxTokens,
      temperature,
      topK,
      topP,
      seed,
      stopSequences,
      images,
      sequenceId,
    ]
  }
  static func == (lhs: GenerationRequest, rhs: GenerationRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.sessionId, rhs.sessionId) && deepEqualsMessages(lhs.prompt, rhs.prompt) && deepEqualsMessages(lhs.maxTokens, rhs.maxTokens) && deepEqualsMessages(lhs.temperature, rhs.temperature) && deepEqualsMessages(lhs.topK, rhs.topK) && deepEqualsMessages(lhs.topP, rhs.topP) && deepEqualsMessages(lhs.seed, rhs.seed) && deepEqualsMessages(lhs.stopSequences, rhs.stopSequences) && deepEqualsMessages(lhs.images, rhs.images) && deepEqualsMessages(lhs.sequenceId, rhs.sequenceId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GenerationRequest")
    deepHashMessages(value: sessionId, hasher: &hasher)
    deepHashMessages(value: prompt, hasher: &hasher)
    deepHashMessages(value: maxTokens, hasher: &hasher)
    deepHashMessages(value: temperature, hasher: &hasher)
    deepHashMessages(value: topK, hasher: &hasher)
    deepHashMessages(value: topP, hasher: &hasher)
    deepHashMessages(value: seed, hasher: &hasher)
    deepHashMessages(value: stopSequences, hasher: &hasher)
    deepHashMessages(value: images, hasher: &hasher)
    deepHashMessages(value: sequenceId, hasher: &hasher)
  }
}

/// Token accounting and timing for one generation run, delivered on the
/// final [TokenEvent].
///
/// Generated class from Pigeon that represents data sent in messages.
struct GenerationStats: Hashable {
  /// Prompt tokens fed to the model (including the reused prefix).
  var promptTokenCount: Int64
  /// Prompt tokens served from the reused KV-cache prefix.
  var cachedTokenCount: Int64
  /// Tokens generated.
  var generatedTokenCount: Int64
  /// Why the run stopped.
  var finishReason: FinishReason
  /// Wall-clock time spent ingesting the prompt, in microseconds.
  var prefillMicroseconds: Int64
  /// Wall-clock time spent in the decode loop, in microseconds.
  var decodeMicroseconds: Int64
  /// Tokens proposed by the draft model across the run; null when the
  /// session runs without speculative decoding.
  var draftedTokenCount: Int64? = nil
  /// Drafted tokens the main model accepted; null when the session runs
  /// without speculative decoding.
  var acceptedTokenCount: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenerationStats? {
    let promptTokenCount = pigeonVar_list[0] as! Int64
    let cachedTokenCount = pigeonVar_list[1] as! Int64
    let generatedTokenCount = pigeonVar_list[2] as! Int64
    let finishReason = pigeonVar_list[3] as! FinishReason
    let prefillMicroseconds = pigeonVar_list[4] as! Int64
    let decodeMicroseconds = pigeonVar_list[5] as! Int64
    let draftedTokenCount: Int64? = nilOrValue(pigeonVar_list[6])
    let acceptedTokenCount: Int64? = nilOrValue(pigeonVar_list[7])

    return GenerationStats(
      promptTokenCount: promptTokenCount,
      cachedTokenCount: cachedTokenCount,
      generatedTokenCount: generatedTokenCount,
      finishReason: finishReason,
      prefillMicroseconds: prefillMicroseconds,
      decodeMicroseconds: decodeMicroseconds,
      draftedTokenCount: draftedTokenCount,
      acceptedTokenCount: acceptedTokenCount
    )
  }
  func toList() -> [Any?] {
    return [
      promptTokenCount,
      cachedTokenCount,
      generatedTokenCount,
      finishReason,
      prefillMicroseconds,
      decodeMicroseconds,
      draftedTokenCount,
      acceptedTokenCount,
    ]
  }
  static func == (lhs: GenerationStats, rhs: GenerationStats) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.promptTokenCount, rhs.promptTokenCount) && deepEqualsMessages(lhs.cachedTokenCount, rhs.cachedTokenCount) && deepEqualsMessages(lhs.generatedTokenCount, rhs.generatedTokenCount) && deepEqualsMessages(lhs.finishReason, rhs.finishReason) && deepEqualsMessages(lhs.prefillMicroseconds, rhs.prefillMicroseconds) && deepEqualsMessages(lhs.decodeMicroseconds, rhs.decodeMicroseconds) && deepEqualsMessages(lhs.draftedTokenCount, rhs.draftedTokenCount) && deepEqualsMessages(lhs.acceptedTokenCount, rhs.acceptedTokenCount)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GenerationStats")
    deepHashMessages(value: promptTokenCount, hasher: &hasher)
    deepHashMessages(value: cachedTokenCount, hasher: &hasher)
    deepHashMessages(value: generatedTokenCount, hasher: &hasher)
    deepHashMessages(value: finishReason, hasher: &hasher)
    deepHashMessages(value: prefillMicroseconds, hasher: &hasher)
    deepHashMessages(value: decodeMicroseconds, hasher: &hasher)
    deepHashMessages(value: draftedTokenCount, hasher: &hasher)
    deepHashMessages(value: acceptedTokenCount, hasher: &hasher)
  }
}

/// A single streamed generation event.
///
/// Emitted repeatedly with [text] set while tokens are produced, then once
/// more with [done] true. On failure [error] is set and [done] is true.
///
/// Generated class from Pigeon that represents data sent in messages.
struct TokenEvent: Hashable {
  var sessionId: Int64
  var text: String? = nil
  var done: Bool
  var error: String? = nil
  /// Accounting for the completed run, set on the `done` event (absent when
  /// [error] is set).
  var stats: GenerationStats? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TokenEvent? {
    let sessionId = pigeonVar_list[0] as! Int64
    let text: String? = nilOrValue(pigeonVar_list[1])
    let done = pigeonVar_list[2] as! Bool
    let error: String? = nilOrValue(pigeonVar_list[3])
    let stats: GenerationStats? = nilOrValue(pigeonVar_list[4])

    return TokenEvent(
      sessionId: sessionId,
      text: text,
      done: done,
      error: error,
      stats: stats
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      text,
      done,
      error,
      stats,
    ]
  }
  static func == (lhs: TokenEvent, rhs: TokenEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.sessionId, rhs.sessionId) && deepEqualsMessages(lhs.text, rhs.text) && deepEqualsMessages(lhs.done, rhs.done) && deepEqualsMessages(lhs.error, rhs.error) && deepEqualsMessages(lhs.stats, rhs.stats)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TokenEvent")
    deepHashMessages(value: sessionId, hasher: &hasher)
    deepHashMessages(value: text, hasher: &hasher)
    deepHashMessages(value: done, hasher: &hasher)
    deepHashMessages(value: error, hasher: &hasher)
    deepHashMessages(value: stats, hasher: &hasher)
  }
}

/// Result of [LlamaHostApi.stashSessionState].
///
/// Generated class from Pigeon that represents data sent in messages.
struct StashResult: Hashable {
  /// Tokens the stashed state covers (`0` = nothing was stashed).
  var tokens: Int64
  /// Size of the stashed blob in bytes (counts against process memory
  /// until dropped or the session is disposed).
  var bytes: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StashResult? {
    let tokens = pigeonVar_list[0] as! Int64
    let bytes = pigeonVar_list[1] as! Int64

    return StashResult(
      tokens: tokens,
      bytes: bytes
    )
  }
  func toList() -> [Any?] {
    return [
      tokens,
      bytes,
    ]
  }
  static func == (lhs: StashResult, rhs: StashResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.tokens, rhs.tokens) && deepEqualsMessages(lhs.bytes, rhs.bytes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StashResult")
    deepHashMessages(value: tokens, hasher: &hasher)
    deepHashMessages(value: bytes, hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FinishReason(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return DraftModelOptions.fromList(self.readValue() as! [Any?])
    case 131:
      return ModelLoadRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return GenerationRequest.fromList(self.readValue() as! [Any?])
    case 133:
      return GenerationStats.fromList(self.readValue() as! [Any?])
    case 134:
      return TokenEvent.fromList(self.readValue() as! [Any?])
    case 135:
      return StashResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? FinishReason {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? DraftModelOptions {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? ModelLoadRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? GenerationRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? GenerationStats {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? TokenEvent {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? StashResult {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

var messagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MessagesPigeonCodecReaderWriter());


/// Control surface implemented natively (Swift) and called from Dart.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LlamaHostApi {
  /// Loads the model and returns an opaque session id.
  func loadModel(request: ModelLoadRequest, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Starts generation; tokens arrive on the [LlamaTokenStream] event channel.
  func startGeneration(request: GenerationRequest) throws
  /// Requests cancellation of an in-flight generation for [sessionId].
  func cancelGeneration(sessionId: Int64) throws
  /// Saves one sequence's KV-cache state (and its token ledger) to [path].
  ///
  /// [sequenceId] null means sequence 0. Returns the number of tokens
  /// covered by the snapshot: positive on success, `0` when the sequence
  /// holds no reusable cache (no file is written). Runs on the session's
  /// serial queue, so it cannot interleave with generation.
  func saveSessionState(sessionId: Int64, path: String, sequenceId: Int64?, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Restores KV-cache state previously written by [saveSessionState] into
  /// [sequenceId] (null = sequence 0).
  ///
  /// Replaces that sequence's current cache contents. Returns the number of
  /// tokens restored. Fails (throws) when the file is missing, corrupt, or
  /// was written by an incompatible model — the sequence is left with an
  /// empty cache in that case, so the next generation simply prefills from
  /// scratch.
  func loadSessionState(sessionId: Int64, path: String, sequenceId: Int64?, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Measures the byte size of one sequence's current state (KV cache plus
  /// bookkeeping) without writing it anywhere.
  ///
  /// This is the exact size [saveSessionState] would write for the current
  /// cache, so orchestrating callers can budget memory or disk before
  /// snapshotting. Runs on the session's serial queue, so it cannot
  /// interleave with generation.
  func getSessionStateSize(sessionId: Int64, sequenceId: Int64?, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Copies one sequence's KV state into an in-memory, native-side stash
  /// under [key], without touching the sequence itself.
  ///
  /// The blob never crosses the platform channel — restoring later is a
  /// RAM-to-RAM copy, far faster than the file path. The stash lives and
  /// dies with the session (disposed with it). An existing entry under
  /// [key] is replaced. Returns zero counts when the sequence holds no
  /// reusable cache (nothing is stashed).
  func stashSessionState(sessionId: Int64, sequenceId: Int64, key: String, completion: @escaping (Result<StashResult, Error>) -> Void)
  /// Restores stashed state saved under [key] into [sequenceId], replacing
  /// that sequence's current cache. The stash entry is kept (drop it
  /// explicitly with [dropStashedState]).
  ///
  /// Returns the number of tokens restored; fails (throws) when [key] has
  /// no entry or the copy fails, leaving the sequence's cache empty.
  func restoreStashedState(sessionId: Int64, sequenceId: Int64, key: String, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Removes the stash entry under [key], freeing its memory. Returns the
  /// number of bytes freed (`0` when no entry existed).
  func dropStashedState(sessionId: Int64, key: String, completion: @escaping (Result<Int64, Error>) -> Void)
  /// Erases one sequence's KV cache and prompt ledger. Queued behind any
  /// in-flight generation like every other session operation.
  func clearSequence(sessionId: Int64, sequenceId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  /// Changes the per-image vision token budget for subsequent image turns
  /// (see [ModelLoadRequest.imageTokenBudget]); null restores the model's
  /// metadata default.
  ///
  /// The mtmd context is freed so the next image turn re-creates it with
  /// the new budget — a projector reload from disk, while the LLM context
  /// and KV caches stay untouched. Fails when the budget exceeds the
  /// micro-batch size fixed at load (`n_ubatch`); raising it beyond that
  /// requires reloading the model.
  func setImageTokenBudget(sessionId: Int64, imageTokenBudget: Int64?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Frees the model/context associated with [sessionId].
  func disposeSession(sessionId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LlamaHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `LlamaHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LlamaHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Loads the model and returns an opaque session id.
    let loadModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.loadModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadModelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ModelLoadRequest
        api.loadModel(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadModelChannel.setMessageHandler(nil)
    }
    /// Starts generation; tokens arrive on the [LlamaTokenStream] event channel.
    let startGenerationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.startGeneration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startGenerationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! GenerationRequest
        do {
          try api.startGeneration(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startGenerationChannel.setMessageHandler(nil)
    }
    /// Requests cancellation of an in-flight generation for [sessionId].
    let cancelGenerationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.cancelGeneration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelGenerationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        do {
          try api.cancelGeneration(sessionId: sessionIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelGenerationChannel.setMessageHandler(nil)
    }
    /// Saves one sequence's KV-cache state (and its token ledger) to [path].
    ///
    /// [sequenceId] null means sequence 0. Returns the number of tokens
    /// covered by the snapshot: positive on success, `0` when the sequence
    /// holds no reusable cache (no file is written). Runs on the session's
    /// serial queue, so it cannot interleave with generation.
    let saveSessionStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.saveSessionState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveSessionStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let pathArg = args[1] as! String
        let sequenceIdArg: Int64? = nilOrValue(args[2])
        api.saveSessionState(sessionId: sessionIdArg, path: pathArg, sequenceId: sequenceIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveSessionStateChannel.setMessageHandler(nil)
    }
    /// Restores KV-cache state previously written by [saveSessionState] into
    /// [sequenceId] (null = sequence 0).
    ///
    /// Replaces that sequence's current cache contents. Returns the number of
    /// tokens restored. Fails (throws) when the file is missing, corrupt, or
    /// was written by an incompatible model — the sequence is left with an
    /// empty cache in that case, so the next generation simply prefills from
    /// scratch.
    let loadSessionStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.loadSessionState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadSessionStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let pathArg = args[1] as! String
        let sequenceIdArg: Int64? = nilOrValue(args[2])
        api.loadSessionState(sessionId: sessionIdArg, path: pathArg, sequenceId: sequenceIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadSessionStateChannel.setMessageHandler(nil)
    }
    /// Measures the byte size of one sequence's current state (KV cache plus
    /// bookkeeping) without writing it anywhere.
    ///
    /// This is the exact size [saveSessionState] would write for the current
    /// cache, so orchestrating callers can budget memory or disk before
    /// snapshotting. Runs on the session's serial queue, so it cannot
    /// interleave with generation.
    let getSessionStateSizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.getSessionStateSize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSessionStateSizeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let sequenceIdArg: Int64? = nilOrValue(args[1])
        api.getSessionStateSize(sessionId: sessionIdArg, sequenceId: sequenceIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getSessionStateSizeChannel.setMessageHandler(nil)
    }
    /// Copies one sequence's KV state into an in-memory, native-side stash
    /// under [key], without touching the sequence itself.
    ///
    /// The blob never crosses the platform channel — restoring later is a
    /// RAM-to-RAM copy, far faster than the file path. The stash lives and
    /// dies with the session (disposed with it). An existing entry under
    /// [key] is replaced. Returns zero counts when the sequence holds no
    /// reusable cache (nothing is stashed).
    let stashSessionStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.stashSessionState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stashSessionStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let sequenceIdArg = args[1] as! Int64
        let keyArg = args[2] as! String
        api.stashSessionState(sessionId: sessionIdArg, sequenceId: sequenceIdArg, key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stashSessionStateChannel.setMessageHandler(nil)
    }
    /// Restores stashed state saved under [key] into [sequenceId], replacing
    /// that sequence's current cache. The stash entry is kept (drop it
    /// explicitly with [dropStashedState]).
    ///
    /// Returns the number of tokens restored; fails (throws) when [key] has
    /// no entry or the copy fails, leaving the sequence's cache empty.
    let restoreStashedStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.restoreStashedState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      restoreStashedStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let sequenceIdArg = args[1] as! Int64
        let keyArg = args[2] as! String
        api.restoreStashedState(sessionId: sessionIdArg, sequenceId: sequenceIdArg, key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      restoreStashedStateChannel.setMessageHandler(nil)
    }
    /// Removes the stash entry under [key], freeing its memory. Returns the
    /// number of bytes freed (`0` when no entry existed).
    let dropStashedStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.dropStashedState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      dropStashedStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let keyArg = args[1] as! String
        api.dropStashedState(sessionId: sessionIdArg, key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      dropStashedStateChannel.setMessageHandler(nil)
    }
    /// Erases one sequence's KV cache and prompt ledger. Queued behind any
    /// in-flight generation like every other session operation.
    let clearSequenceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.clearSequence\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearSequenceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let sequenceIdArg = args[1] as! Int64
        api.clearSequence(sessionId: sessionIdArg, sequenceId: sequenceIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearSequenceChannel.setMessageHandler(nil)
    }
    /// Changes the per-image vision token budget for subsequent image turns
    /// (see [ModelLoadRequest.imageTokenBudget]); null restores the model's
    /// metadata default.
    ///
    /// The mtmd context is freed so the next image turn re-creates it with
    /// the new budget — a projector reload from disk, while the LLM context
    /// and KV caches stay untouched. Fails when the budget exceeds the
    /// micro-batch size fixed at load (`n_ubatch`); raising it beyond that
    /// requires reloading the model.
    let setImageTokenBudgetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.setImageTokenBudget\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setImageTokenBudgetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let imageTokenBudgetArg: Int64? = nilOrValue(args[1])
        api.setImageTokenBudget(sessionId: sessionIdArg, imageTokenBudget: imageTokenBudgetArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setImageTokenBudgetChannel.setMessageHandler(nil)
    }
    /// Frees the model/context associated with [sessionId].
    let disposeSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter.LlamaHostApi.disposeSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        do {
          try api.disposeSession(sessionId: sessionIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeSessionChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

/// Token stream delivered from native to Dart via an `EventChannel`.
///
/// A single stream multiplexes every session's tokens; each [TokenEvent]
/// carries its [TokenEvent.sessionId] so listeners can filter per session.
class StreamTokensStreamHandler: PigeonEventChannelWrapper<TokenEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: StreamTokensStreamHandler) {
    var channelName = "dev.flutter.pigeon.llama_flutter.LlamaTokenStream.streamTokens"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<TokenEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
