// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Why a generation run stopped.
enum FinishReason {
  /// The model produced an end-of-generation token.
  eogToken,
  /// The run reached [GenerationRequest.maxTokens].
  maxTokens,
  /// A [GenerationRequest.stopSequences] entry matched.
  stopSequence,
  /// The context window filled before the run ended naturally.
  contextFull,
  /// The run was cancelled via [LlamaHostApi.cancelGeneration].
  cancelled,
  /// The native runtime ended the run early after an unrecoverable internal
  /// condition (e.g. a failed speculative rollback). Text streamed before
  /// this point is valid.
  aborted,
}

/// Parameters for an optional drafter (assistant) model that enables
/// speculative decoding.
///
/// The drafter proposes tokens cheaply and the main model verifies them, so
/// the output distribution is identical to decoding with the main model
/// alone — just faster when the drafter's guesses are accepted. Any GGUF
/// whose vocabulary matches the main model works (e.g. a Gemma 4 MTP
/// `*-assistant` drafter); this is not tied to one architecture.
class DraftModelOptions {
  DraftModelOptions({
    required this.modelPath,
    required this.gpuLayers,
    required this.maxDraftTokens,
  });

  /// Absolute filesystem path to the drafter `.gguf`.
  String modelPath;

  /// Number of drafter layers to offload to the GPU (`n_gpu_layers`).
  ///
  /// `0` forces CPU-only inference (e.g. the iOS Simulator).
  int gpuLayers;

  /// Maximum tokens drafted per verification step.
  int maxDraftTokens;

  List<Object?> _toList() {
    return <Object?>[
      modelPath,
      gpuLayers,
      maxDraftTokens,
    ];
  }

  Object encode() {
    return _toList();  }

  static DraftModelOptions decode(Object result) {
    result as List<Object?>;
    return DraftModelOptions(
      modelPath: result[0]! as String,
      gpuLayers: result[1]! as int,
      maxDraftTokens: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DraftModelOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(modelPath, other.modelPath) && _deepEquals(gpuLayers, other.gpuLayers) && _deepEquals(maxDraftTokens, other.maxDraftTokens);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Parameters for loading a GGUF model into a native llama.cpp session.
class ModelLoadRequest {
  ModelLoadRequest({
    required this.modelPath,
    required this.contextSize,
    required this.gpuLayers,
    this.mmprojPath,
    this.imageTokenBudget,
    this.draftModel,
    this.maxSequences,
  });

  /// Absolute filesystem path to the `.gguf` model.
  String modelPath;

  /// Context window size (`n_ctx`).
  int contextSize;

  /// Number of layers to offload to the GPU (`n_gpu_layers`).
  ///
  /// `0` forces CPU-only inference (e.g. the iOS Simulator).
  int gpuLayers;

  /// Absolute path to the multimodal projector (`mmproj`) `.gguf`.
  ///
  /// When non-null the session also stands up an `mtmd` context, enabling
  /// image input via [GenerationRequest.images]. Null keeps the session
  /// text-only.
  String? mmprojPath;

  /// Vision-encoder token budget per image (mtmd `image_min_tokens` and
  /// `image_max_tokens`, both set to this value).
  ///
  /// Only meaningful with [mmprojPath], for vision models with dynamic
  /// resolution. Gemma supports 70, 140, 280, 560, or 1120; higher budgets
  /// trade prefill time for fidelity (1120 suits OCR / small text). Null
  /// keeps the model's metadata default. The physical batch is floored at
  /// this value so the encoder's non-causal image chunk fits one ubatch.
  int? imageTokenBudget;

  /// Optional drafter model enabling speculative decoding.
  ///
  /// Null disables speculation; the session then behaves exactly as a
  /// single-model session.
  DraftModelOptions? draftModel;

  /// Number of independent KV-cache sequences the context supports
  /// (`n_seq_max`). Null or `1` keeps the classic single-sequence session.
  ///
  /// With N sequences, [contextSize] is the TOTAL KV budget and each
  /// sequence gets `contextSize / N` positions. Generations target a
  /// sequence via [GenerationRequest.sequenceId]. Speculative decoding
  /// (draft models) only runs on sequence 0.
  int? maxSequences;

  List<Object?> _toList() {
    return <Object?>[
      modelPath,
      contextSize,
      gpuLayers,
      mmprojPath,
      imageTokenBudget,
      draftModel,
      maxSequences,
    ];
  }

  Object encode() {
    return _toList();  }

  static ModelLoadRequest decode(Object result) {
    result as List<Object?>;
    return ModelLoadRequest(
      modelPath: result[0]! as String,
      contextSize: result[1]! as int,
      gpuLayers: result[2]! as int,
      mmprojPath: result[3] as String?,
      imageTokenBudget: result[4] as int?,
      draftModel: result[5] as DraftModelOptions?,
      maxSequences: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ModelLoadRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(modelPath, other.modelPath) && _deepEquals(contextSize, other.contextSize) && _deepEquals(gpuLayers, other.gpuLayers) && _deepEquals(mmprojPath, other.mmprojPath) && _deepEquals(imageTokenBudget, other.imageTokenBudget) && _deepEquals(draftModel, other.draftModel) && _deepEquals(maxSequences, other.maxSequences);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Parameters for a single generation run against a loaded session.
class GenerationRequest {
  GenerationRequest({
    required this.sessionId,
    required this.prompt,
    required this.maxTokens,
    required this.temperature,
    this.topK,
    this.topP,
    this.seed,
    required this.stopSequences,
    this.images,
    this.sequenceId,
  });

  /// Session returned by [LlamaHostApi.loadModel].
  int sessionId;

  /// The fully formatted prompt to feed the model.
  String prompt;

  /// Hard cap on the number of tokens to generate.
  int maxTokens;

  /// Sampling temperature; `0` is greedy.
  double temperature;

  /// Top-k cutoff applied before temperature sampling. Null or `<= 0`
  /// disables the top-k stage.
  int? topK;

  /// Nucleus (top-p) cutoff applied before temperature sampling. Null or
  /// `>= 1.0` disables the top-p stage.
  double? topP;

  /// Sampler seed for reproducible generation. Null draws a random seed.
  int? seed;

  /// Strings that, when produced in the decoded output, halt generation.
  ///
  /// The matched stop sequence is removed from the streamed text and is not
  /// emitted. Matching runs against the decoded text (with special tokens
  /// rendered), so control markers such as Gemma's `<turn|>` work directly.
  /// Empty disables stop-sequence handling.
  List<String> stopSequences;

  /// Encoded image bytes (PNG/JPEG) to feed alongside [prompt].
  ///
  /// Each entry corresponds, in order, to one media marker in [prompt]. Only
  /// honoured when the session was loaded with a
  /// [ModelLoadRequest.mmprojPath]; otherwise ignored. Null or empty runs a
  /// text-only generation.
  List<Uint8List>? images;

  /// KV-cache sequence this generation runs in. Null means sequence 0.
  ///
  /// Only meaningful when the session was loaded with
  /// [ModelLoadRequest.maxSequences] > 1; each sequence keeps its own
  /// prompt-prefix cache. Speculative decoding is bypassed for non-zero
  /// sequences.
  int? sequenceId;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      prompt,
      maxTokens,
      temperature,
      topK,
      topP,
      seed,
      stopSequences,
      images,
      sequenceId,
    ];
  }

  Object encode() {
    return _toList();  }

  static GenerationRequest decode(Object result) {
    result as List<Object?>;
    return GenerationRequest(
      sessionId: result[0]! as int,
      prompt: result[1]! as String,
      maxTokens: result[2]! as int,
      temperature: result[3]! as double,
      topK: result[4] as int?,
      topP: result[5] as double?,
      seed: result[6] as int?,
      stopSequences: (result[7]! as List<Object?>).cast<String>(),
      images: (result[8] as List<Object?>?)?.cast<Uint8List>(),
      sequenceId: result[9] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GenerationRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(prompt, other.prompt) && _deepEquals(maxTokens, other.maxTokens) && _deepEquals(temperature, other.temperature) && _deepEquals(topK, other.topK) && _deepEquals(topP, other.topP) && _deepEquals(seed, other.seed) && _deepEquals(stopSequences, other.stopSequences) && _deepEquals(images, other.images) && _deepEquals(sequenceId, other.sequenceId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Token accounting and timing for one generation run, delivered on the
/// final [TokenEvent].
class GenerationStats {
  GenerationStats({
    required this.promptTokenCount,
    required this.cachedTokenCount,
    required this.generatedTokenCount,
    required this.finishReason,
    required this.prefillMicroseconds,
    required this.decodeMicroseconds,
    this.draftedTokenCount,
    this.acceptedTokenCount,
  });

  /// Prompt tokens fed to the model (including the reused prefix).
  int promptTokenCount;

  /// Prompt tokens served from the reused KV-cache prefix.
  int cachedTokenCount;

  /// Tokens generated.
  int generatedTokenCount;

  /// Why the run stopped.
  FinishReason finishReason;

  /// Wall-clock time spent ingesting the prompt, in microseconds.
  int prefillMicroseconds;

  /// Wall-clock time spent in the decode loop, in microseconds.
  int decodeMicroseconds;

  /// Tokens proposed by the draft model across the run; null when the
  /// session runs without speculative decoding.
  int? draftedTokenCount;

  /// Drafted tokens the main model accepted; null when the session runs
  /// without speculative decoding.
  int? acceptedTokenCount;

  List<Object?> _toList() {
    return <Object?>[
      promptTokenCount,
      cachedTokenCount,
      generatedTokenCount,
      finishReason,
      prefillMicroseconds,
      decodeMicroseconds,
      draftedTokenCount,
      acceptedTokenCount,
    ];
  }

  Object encode() {
    return _toList();  }

  static GenerationStats decode(Object result) {
    result as List<Object?>;
    return GenerationStats(
      promptTokenCount: result[0]! as int,
      cachedTokenCount: result[1]! as int,
      generatedTokenCount: result[2]! as int,
      finishReason: result[3]! as FinishReason,
      prefillMicroseconds: result[4]! as int,
      decodeMicroseconds: result[5]! as int,
      draftedTokenCount: result[6] as int?,
      acceptedTokenCount: result[7] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GenerationStats || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(promptTokenCount, other.promptTokenCount) && _deepEquals(cachedTokenCount, other.cachedTokenCount) && _deepEquals(generatedTokenCount, other.generatedTokenCount) && _deepEquals(finishReason, other.finishReason) && _deepEquals(prefillMicroseconds, other.prefillMicroseconds) && _deepEquals(decodeMicroseconds, other.decodeMicroseconds) && _deepEquals(draftedTokenCount, other.draftedTokenCount) && _deepEquals(acceptedTokenCount, other.acceptedTokenCount);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// A single streamed generation event.
///
/// Emitted repeatedly with [text] set while tokens are produced, then once
/// more with [done] true. On failure [error] is set and [done] is true.
class TokenEvent {
  TokenEvent({
    required this.sessionId,
    this.text,
    required this.done,
    this.error,
    this.stats,
  });

  int sessionId;

  String? text;

  bool done;

  String? error;

  /// Accounting for the completed run, set on the `done` event (absent when
  /// [error] is set).
  GenerationStats? stats;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      text,
      done,
      error,
      stats,
    ];
  }

  Object encode() {
    return _toList();  }

  static TokenEvent decode(Object result) {
    result as List<Object?>;
    return TokenEvent(
      sessionId: result[0]! as int,
      text: result[1] as String?,
      done: result[2]! as bool,
      error: result[3] as String?,
      stats: result[4] as GenerationStats?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TokenEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(text, other.text) && _deepEquals(done, other.done) && _deepEquals(error, other.error) && _deepEquals(stats, other.stats);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Result of [LlamaHostApi.stashSessionState].
class StashResult {
  StashResult({
    required this.tokens,
    required this.bytes,
  });

  /// Tokens the stashed state covers (`0` = nothing was stashed).
  int tokens;

  /// Size of the stashed blob in bytes (counts against process memory
  /// until dropped or the session is disposed).
  int bytes;

  List<Object?> _toList() {
    return <Object?>[
      tokens,
      bytes,
    ];
  }

  Object encode() {
    return _toList();  }

  static StashResult decode(Object result) {
    result as List<Object?>;
    return StashResult(
      tokens: result[0]! as int,
      bytes: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StashResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(tokens, other.tokens) && _deepEquals(bytes, other.bytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is FinishReason) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is DraftModelOptions) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is ModelLoadRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is GenerationRequest) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is GenerationStats) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is TokenEvent) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is StashResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : FinishReason.values[value];
      case 130:
        return DraftModelOptions.decode(readValue(buffer)!);
      case 131:
        return ModelLoadRequest.decode(readValue(buffer)!);
      case 132:
        return GenerationRequest.decode(readValue(buffer)!);
      case 133:
        return GenerationStats.decode(readValue(buffer)!);
      case 134:
        return TokenEvent.decode(readValue(buffer)!);
      case 135:
        return StashResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

/// Control surface implemented natively (Swift) and called from Dart.
class LlamaHostApi {
  /// Constructor for [LlamaHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LlamaHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Loads the model and returns an opaque session id.
  Future<int> loadModel(ModelLoadRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.loadModel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Starts generation; tokens arrive on the [LlamaTokenStream] event channel.
  Future<void> startGeneration(GenerationRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.startGeneration$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Requests cancellation of an in-flight generation for [sessionId].
  Future<void> cancelGeneration(int sessionId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.cancelGeneration$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Saves one sequence's KV-cache state (and its token ledger) to [path].
  ///
  /// [sequenceId] null means sequence 0. Returns the number of tokens
  /// covered by the snapshot: positive on success, `0` when the sequence
  /// holds no reusable cache (no file is written). Runs on the session's
  /// serial queue, so it cannot interleave with generation.
  Future<int> saveSessionState(int sessionId, String path, int? sequenceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.saveSessionState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, path, sequenceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Restores KV-cache state previously written by [saveSessionState] into
  /// [sequenceId] (null = sequence 0).
  ///
  /// Replaces that sequence's current cache contents. Returns the number of
  /// tokens restored. Fails (throws) when the file is missing, corrupt, or
  /// was written by an incompatible model — the sequence is left with an
  /// empty cache in that case, so the next generation simply prefills from
  /// scratch.
  Future<int> loadSessionState(int sessionId, String path, int? sequenceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.loadSessionState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, path, sequenceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Measures the byte size of one sequence's current state (KV cache plus
  /// bookkeeping) without writing it anywhere.
  ///
  /// This is the exact size [saveSessionState] would write for the current
  /// cache, so orchestrating callers can budget memory or disk before
  /// snapshotting. Runs on the session's serial queue, so it cannot
  /// interleave with generation.
  Future<int> getSessionStateSize(int sessionId, int? sequenceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.getSessionStateSize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, sequenceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Copies one sequence's KV state into an in-memory, native-side stash
  /// under [key], without touching the sequence itself.
  ///
  /// The blob never crosses the platform channel — restoring later is a
  /// RAM-to-RAM copy, far faster than the file path. The stash lives and
  /// dies with the session (disposed with it). An existing entry under
  /// [key] is replaced. Returns zero counts when the sequence holds no
  /// reusable cache (nothing is stashed).
  Future<StashResult> stashSessionState(int sessionId, int sequenceId, String key) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.stashSessionState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, sequenceId, key]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as StashResult;
  }

  /// Restores stashed state saved under [key] into [sequenceId], replacing
  /// that sequence's current cache. The stash entry is kept (drop it
  /// explicitly with [dropStashedState]).
  ///
  /// Returns the number of tokens restored; fails (throws) when [key] has
  /// no entry or the copy fails, leaving the sequence's cache empty.
  Future<int> restoreStashedState(int sessionId, int sequenceId, String key) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.restoreStashedState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, sequenceId, key]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Removes the stash entry under [key], freeing its memory. Returns the
  /// number of bytes freed (`0` when no entry existed).
  Future<int> dropStashedState(int sessionId, String key) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.dropStashedState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, key]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  /// Erases one sequence's KV cache and prompt ledger. Queued behind any
  /// in-flight generation like every other session operation.
  Future<void> clearSequence(int sessionId, int sequenceId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.clearSequence$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, sequenceId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Changes the per-image vision token budget for subsequent image turns
  /// (see [ModelLoadRequest.imageTokenBudget]); null restores the model's
  /// metadata default.
  ///
  /// The mtmd context is freed so the next image turn re-creates it with
  /// the new budget — a projector reload from disk, while the LLM context
  /// and KV caches stay untouched. Fails when the budget exceeds the
  /// micro-batch size fixed at load (`n_ubatch`); raising it beyond that
  /// requires reloading the model.
  Future<void> setImageTokenBudget(int sessionId, int? imageTokenBudget) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.setImageTokenBudget$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, imageTokenBudget]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Frees the model/context associated with [sessionId].
  Future<void> disposeSession(int sessionId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter.LlamaHostApi.disposeSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// Token stream delivered from native to Dart via an `EventChannel`.
///
/// A single stream multiplexes every session's tokens; each [TokenEvent]
/// carries its [TokenEvent.sessionId] so listeners can filter per session.
Stream<TokenEvent> streamTokens( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel streamTokensChannel =
      EventChannel('dev.flutter.pigeon.llama_flutter.LlamaTokenStream.streamTokens$instanceName', pigeonMethodCodec);
  return streamTokensChannel.receiveBroadcastStream().map((dynamic event) {
    return event as TokenEvent;
  });
}
    
